GraniteHouse/Models/Appointments.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
namespace GraniteHouse.Models
{
    public class Appointments
    {
       
        public int Id { get; set; }

        [Display(Name ="Sales Person")]
        public string SalesPersonId { get; set; }

        [ForeignKey("SalesPersonId")]
        public virtual ApplicationUser SalesPerson { get; set; }
        [Display(Name = "Created Date")]
        public DateTime AppointmentCreatedDate { get; set; }
        [Display(Name = "Delivery Date")]
        public DateTime AppointmentDate { get; set; }
        [Display(Name = "Customer Name")]
        public string CustomerName { get; set; }
        [Display(Name = "Customer Phone")]
        public string CustomerPhoneNumber { get; set; }
        [ForeignKey("CustomerPhoneNumber")]
        public virtual Customer Customer { get; set; }
        [Display(Name = "Customer Email")]
        public string CustomerEmail { get; set; }
        [Display(Name = "Customer Address")]
        public string CustomerAddress { get; set; }
        [Display(Name = "Confirmed")]
        public bool isConfirmed { get; set; }
        [Display(Name = "Completed")]
        public bool isCompleted { get; set; }

        [Column(TypeName = "decimal(18,4)")]
        [Display(Name = "Total")]
        public decimal TotalAppointment { get; set; }

        public string Note { get; set; }


    }
}

GraniteHouse/Models/ViewModel/AppointmentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GraniteHouse.Models.ViewModel
{
    public class AppointmentViewModel
    {
        public List<Appointments> Appointments { get; set; }
        public PagingInfo PagingInfo { get; set; }
        
    }
}

GraniteHouse/Areas/Admin/Controllers/AppointmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using GraniteHouse.Data;
using GraniteHouse.Models;
using GraniteHouse.Models.ViewModel;
using GraniteHouse.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GraniteHouse.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.AdminEndUser + "," + SD.SuperAdminEndUser)]
    [Area("Admin")]
    public class AppointmentsController : Controller
    {

        private readonly ApplicationDbContext _db;
        private int PageSize = 6;

        public AppointmentsController(ApplicationDbContext db)
        {
            _db = db;
        }

       
        public async Task<IActionResult> Index(int productPage = 1, string searchName = null, string searchEmail = null, 
            string searchPhone = null, string searchDate = null,string OrderN=null, string OrderS = null, string OrderC = null)
        {
            System.Security.Claims.ClaimsPrincipal currentUser = this.User;
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            AppointmentViewModel appointmentVM = new AppointmentViewModel()
            {
                Appointments = new List<Models.Appointments>()
            };

            StringBuilder param = new StringBuilder();

            param.Append("/Admin/Appointments?productPage=:");
            param.Append("&OrderN=");
            if (OrderN == "NewOrder")
            {
                param.Append(OrderN);
            }
            param.Append("&OrderS=");
            if (OrderS == "ShippingOrder")
            {
                param.Append(OrderS);
            }
            param.Append("&OrderC=");
            if (OrderC == "CompletedOrder")
            {
                param.Append(OrderC);
            }
            param.Append("&searchName=");
            if (searchName != null)
            {
                param.Append(searchName);
            }
            param.Append("&searchEmail=");
            if (searchEmail != null)
            {
                param.Append(searchEmail);
            }
            param.Append("&searchPhone=");
            if (searchPhone != null)
            {
                param.Append(searchPhone);
            }
            param.Append("&searchDate=");
            if (searchDate != null)
            {
                param.Append(searchDate);
            }




            appointmentVM.Appointments = _db.Appointments.Include(a => a.SalesPerson).OrderBy(a=>a.AppointmentCreatedDate).ToList();
            if (User.IsInRole(SD.AdminEndUser))
            {
                appointmentVM.Appointments = appointmentVM.Appointments.Where(a => a.SalesPersonId == claim.Value).OrderBy(a=>a.AppointmentCreatedDate).ToList();
            }

            if(OrderN == "NewOrder")
            {
                appointmentVM.Appointments = appointmentVM.Appointments.Where(a => a.isConfirmed == false && a.isCompleted == false).OrderBy(a => a.AppointmentCreatedDate).ToList();
            }
            if (OrderS == "ShippingOrder")
            {
                appointmentVM.Appointments = appointmentVM.Appointments.Where(a => a.isConfirmed == true && a.isCompleted == false).OrderBy(a => a.AppointmentCreatedDate).ToList();
            }
            if (OrderC == "CompletedOrder")
            {
                appointmentVM.Appointments = appointmentVM.Appointments.Where(a => a.isConfirmed == true && a.isCompleted == true).OrderBy(a => a.AppointmentCreatedDate).ToList();
            }
            if (searchName != null)
            {
                appointmentVM.Appointments = appointmentVM.Appointments.Where(a => a.CustomerName.ToLower().Contains(searchName.ToLower())).OrderBy(a => a.AppointmentCreatedDate).ToList();
            }
            if (searchEmail != null)
            {
                appointmentVM.Appointments = appointmentVM.Appointments.Where(a => a.CustomerEmail.ToLower().Contains(searchEmail.ToLower())).OrderBy(a => a.AppointmentCreatedDate).ToList();
            }
            if (searchPhone != null)
            {
                appointmentVM.Appointments = appointmentVM.Appointments.Where(a => a.CustomerPhoneNumber.ToLower().Contains(searchPhone.ToLower())).OrderBy(a => a.AppointmentCreatedDate).ToList();
            }
            if (searchDate != null)
            {
                try
                {
                    DateTime appDate = Convert.ToDateTime(searchDate);
                    appointmentVM.Appointments = appointmentVM.Appointments.Where(a => a.AppointmentDate.ToShortDateString().Equals(appDate.ToShortDateString())).OrderBy(a => a.AppointmentCreatedDate).ToList();
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }

            }

            var count = appointmentVM.Appointments.Count;

            appointmentVM.Appointments = appointmentVM.Appointments.OrderBy(p => p.AppointmentCreatedDate)
                .Skip((productPage - 1) * PageSize)
                .Take(PageSize).ToList();


            appointmentVM.PagingInfo = new PagingInfo
            {
                CurrentPage = productPage,
                ItemsPerPage = PageSize,
                TotalItems = count,
                urlParam = param.ToString()
            };


            return View(appointmentVM);
        }

        //GET Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var productList2 = (IEnumerable<Products>)(from p in _db.Products
                                                      join a in _db.ProductsSelectedForAppointment
                                                      on p.Id equals a.ProductId
                                                      where a.AppointmentId == id
                                                      select p).Include("ProductTypes").Include("Brand");
            
            var productList = (IEnumerable<ProductsSelectedForAppointment>)(from p in _db.Appointments
                                                                            join a in _db.ProductsSelectedForAppointment
                                                                            on p.Id equals a.AppointmentId
                                                                            where a.AppointmentId == id
                                                                            select a);
            AppointmentDetailsViewModel objAppointmentVM = new AppointmentDetailsViewModel()
            {
                Appointment = _db.Appointments.Include(a => a.SalesPerson).Where(a => a.Id == id).FirstOrDefault(),
                SalesPerson = _db.ApplicationUser.ToList(),
                ProductsSelectedForAppointments = productList.ToList(),
                Products=productList2.ToList()
            };

            return View(objAppointmentVM);

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, AppointmentDetailsViewModel objAppointmentVM,string strUrl)
        {
            if (ModelState.IsValid)
            {


                var appointmentFromDb = _db.Appointments.Where(a => a.Id == objAppointmentVM.Appointment.Id).FirstOrDefault();

                appointmentFromDb.CustomerName = objAppointmentVM.Appointment.CustomerName;
                appointmentFromDb.CustomerEmail = objAppointmentVM.Appointment.CustomerEmail;
                appointmentFromDb.CustomerAddress = objAppointmentVM.Appointment.CustomerAddress;
                appointmentFromDb.AppointmentDate = objAppointmentVM.Appointment.AppointmentDate;
                appointmentFromDb.isConfirmed = objAppointmentVM.Appointment.isConfirmed;
                appointmentFromDb.isCompleted = objAppointmentVM.Appointment.isCompleted;
                if (User.IsInRole(SD.SuperAdminEndUser))
                {
                    appointmentFromDb.SalesPersonId = objAppointmentVM.Appointment.SalesPersonId;
                }
                else
                {
                    appointmentFromDb.SalesPersonId = null;
                }
                _db.SaveChanges();

                return Redirect(strUrl);


            }

            return View(objAppointmentVM);
        }


        //GET Detials
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var productList2 = (IEnumerable<Products>)(from p in _db.Products
                                                      join a in _db.ProductsSelectedForAppointment
                                                      on p.Id equals a.ProductId
                                                      where a.AppointmentId == id
                                                      select p).Include("ProductTypes").Include("Brand");
            
            var productList = (IEnumerable<ProductsSelectedForAppointment>)(from p in _db.Appointments
                                                                            join a in _db.ProductsSelectedForAppointment
                                                                            on p.Id equals a.AppointmentId
                                                                            where a.AppointmentId == id
                                                                            select a);
            AppointmentDetailsViewModel objAppointmentVM = new AppointmentDetailsViewModel()
            {
                Appointment = _db.Appointments.Include(a => a.SalesPerson).Where(a => a.Id == id).FirstOrDefault(),

GraniteHouse/Areas/Customer/Controllers/AppointmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GraniteHouse.interfaces;
using GraniteHouse.Respositories;
using GraniteHouse.Models;
using GraniteHouse.Data;
using GraniteHouse.Models.ViewModel;
using Microsoft.EntityFrameworkCore;

namespace GraniteHouse.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class AppointmentsController : Controller
    {
        private readonly IOrderRepository _orderRepository;
        private readonly ShoppingCart _shoppingCart;
        private readonly ApplicationDbContext _db;

        public AppointmentsController(IOrderRepository orderRepository,ShoppingCart shoppingCart, ApplicationDbContext db)
        {
            _orderRepository = orderRepository;
            _shoppingCart = shoppingCart;
            _db = db;
        }
        public IActionResult Checkout()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Checkout(Appointments appointments)
        {
            var cart = _shoppingCart.GetShoppingCartItems();
            
            if(cart==null||cart.Count==0)
            {
                ModelState.AddModelError("", "Your Bag is empty, add contents first!");
            }          
            else
            {
                string cusName = HttpContext.Request.Form["cusName"];
                string cusPhone = HttpContext.Request.Form["cusPhone"];
                string cusMail = HttpContext.Request.Form["cusMail"];
                string cusAddress = HttpContext.Request.Form["cusAddress"];
                string note = HttpContext.Request.Form["note"];

                Models.Customer Newcustomer = new Models.Customer();
                var cus = _db.Customers.FirstOrDefault(p => p.CusPhone.Equals(cusPhone));

                if (cus != null)
                {
                    cus.CusName = cusName;
                    cus.CusEmail = cusMail;
                    cus.CusAddress = cusAddress;
                    _db.Customers.Update(cus);
                }
                else
                {
                    Newcustomer.CusPhone = cusPhone;
                    Newcustomer.CusName = cusName;
                    Newcustomer.CusEmail = cusMail;
                    Newcustomer.CusAddress = cusAddress;
                    _db.Customers.Add(Newcustomer);
                }
                appointments.Note = note;
                appointments.CustomerAddress = cusAddress;
                appointments.CustomerEmail = cusMail;
                appointments.CustomerName = cusName;
                appointments.CustomerPhoneNumber = cusPhone;
                appointments.AppointmentCreatedDate = DateTime.Now;
                appointments.AppointmentDate = DateTime.Now;
                appointments.isCompleted = false;
                appointments.isConfirmed = false;
                decimal Total = 0;
                foreach (var items in cart)
                {

                    decimal newPrice = (items.Products.Price - ((items.Products.Price * items.Products.Discount) / 100));


                    if (items.Products.Price > newPrice)
                    {
                        Total += (newPrice * items.Amount);
                    }
                    else
                    {
                        Total += (items.Products.Price * items.Amount);
                    }
                    appointments.TotalAppointment = Total;
                }
                _db.Appointments.Add(appointments);

                if (ModelState.IsValid)
                {
                    _orderRepository.CreateOrder(appointments);
                    _shoppingCart.ClearCart();
                    return RedirectToAction("CheckoutComplete");
                }
                _db.SaveChanges();
                return View(appointments);
            }

            return RedirectToAction("EmptyBag");
        }

        public IActionResult CheckoutComplete()
        {
            ViewBag.chekcoutCompleteMessage = " Thanks For Your Order ! ^.^ ";
            return View();
        }
        public IActionResult EmptyBag()
        {
            return View();
        }
    }
}

GraniteHouse/Areas/Admin/Views/Appointments/Edit.cshtml
@model GraniteHouse.Models.ViewModel.AppointmentDetailsViewModel
@using GraniteHouse.Extensions
@using GraniteHouse.Utility
@using Microsoft.AspNetCore.Http.Extensions
@{
    ViewData["Title"] = "Edit";
}


<form method="post" enctype="multipart/form-data">
    <div class="container-fluid">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h2 class="text-info">Edit Order</h2>
                <div class="text-right">
                    <a asp-action="Invoice" asp-controller="Appointments" asp-route-id="@Model.Appointment.Id"  target="_blank"><i class="fa fa-print" style="font-size:30px;"></i></a>
                </div>
                
            </div>
            <div class="p-4 rounded row">
                <input hidden asp-for="Appointment.Id" />
                <input hidden asp-for="Appointment.AppointmentCreatedDate" />
                <input hidden asp-for="Appointment.CustomerPhoneNumber" />
                <input hidden asp-for="Appointment.TotalAppointment" />
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="col-6">
                    <div class="form-group row">
                        <div class="col-4">
                            <label asp-for="Appointment.CustomerName"></label>
                        </div>
                        <div class="col-8">
                            <input asp-for="Appointment.CustomerName" class="form-control" />
                        </div>
                        <span asp-validation-for="Appointment.CustomerName" class="text-danger"></span>
                    </div>
                    <div class="form-group row">
                        <div class="col-4">
                            <label asp-for="Appointment.CustomerPhoneNumber"></label>
                        </div>
                        <div class="col-8">
                            <input asp-for="Appointment.CustomerPhoneNumber" disabled class="form-control" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-4">
                            <label asp-for="Appointment.CustomerEmail"></label>
                        </div>
                        <div class="col-8">
                            <input asp-for="Appointment.CustomerEmail" class="form-control" />
                        </div>
                        <span asp-validation-for="Appointment.CustomerEmail" class="text-danger"></span>
                    </div>
                    <div class="form-group row">
                        <div class="col-4">
                            <label asp-for="Appointment.CustomerAddress"></label>
                        </div>
                        <div class="col-8">
                            <textarea asp-for="Appointment.CustomerAddress" class="form-control" rows="6" style="height:50px;"></textarea>
                        </div>
                        <span asp-validation-for="Appointment.CustomerAddress" class="text-danger"></span>
                    </div>
                    <div class="form-group row">
                        <div class="col-4">
                            <label asp-for="Appointment.Note"></label>
                        </div>
                        <div class="col-8">
                            <textarea asp-for="Appointment.Note" class="form-control" rows="6" style="height:50px;"></textarea>
                        </div>
                        <span asp-validation-for="Appointment.Note" class="text-danger"></span>
                    </div>
                    <div class="form-group row">
                        <div class="col-4">
                            <label asp-for="Appointment.TotalAppointment"></label>
                        </div>
                        <div class="col-8">
                            @{
                                string p = String.Format("{0:0,0}", Model.Appointment.TotalAppointment);
                            }
                            <input asp-for="@p" disabled class="form-control" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-4">
                            <label asp-for="Appointment.AppointmentCreatedDate"></label>
                        </div>
                        <div class="col-8">
                            <input asp-for="Appointment.AppointmentCreatedDate" id="datepicker" disabled type="text" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-4">
                            <label>Delivery Date(*)</label>
                        </div>
                        <div class="col-8">
                            <input asp-for="Appointment.AppointmentDate" id="datepicker2" type="text" class="form-control" />
                        </div>
                        <span asp-validation-for="Appointment.AppointmentDate" class="text-danger"></span>
                    </div>

                    <div class="form-group row">
                        <div class="col-4">
                            <label>Sales Person(*)</label>
                        </div>
                        <div class="col-8">
                            @if (User.IsInRole(SD.AdminEndUser))
                            {
                                <input asp-for="@Model.Appointment.SalesPerson.Name" readonly class="form-control" />
                                <input asp-for="@Model.Appointment.SalesPersonId" hidden />

                            }
                            else
                            {
                                <select asp-for="@Model.Appointment.SalesPersonId" asp-items="Model.SalesPerson.ToSelectListItemString(Model.Appointment.SalesPersonId)" class="form-control"></select>

                            }
                        </div>

                    </div>
                    <div class="form-group row">
                        <div class="col-4">
                            <label>isConfirmed(*)</label>
                        </div>
                        <div class="col-8">
                            <input asp-for="Appointment.isConfirmed" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-4">
                            <label>isCompleted(*)</label>
                        </div>
                        <div class="col-8">
                            <input asp-for="Appointment.isCompleted" class="form-control" />
                        </div>
                    </div>

                </div>
                <div class="col-6">
                    @* Partial View *@
                    <partial name="~/Views/Shared/_AppointmentProductDetails.cshtml" model="Model.ProductsSelectedForAppointments" />
                </div>



                <br />
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" asp-route-strUrl="@Context.Request.GetDisplayUrl()" value="Update"/>
                    <a asp-action="Index" class="btn btn-success">Back to List</a>
                </div>
            </div>
        </div>
    </div>
   
</form>


@section Scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $('.timepicker').timepicker({
            timeFormat: 'h:mm p',
            interval: 30,
            minTime: '10',
            maxTime: '3:00pm',
            startTime: '10:00',
            dynamic: true,
            dropdown: true,
            scrollbar: true
        });

        $(function () {
            $("#datepicker").datepicker({
                minDate: +0, maxDate: "+3M"
            });
        });

        $(document).ready(function () {
            var appointmentTime = document.getElementById('datepicker').value;
            var splitData = "";
            if (appointmentTime.indexOf(" ") > 0) {
                splitData = appointmentTime.split(" ");

            }
            else {
                splitData = appointmentTime.split("T");

            }

            var time = splitData[1].substring(0, 5);
            if (time.slice(-1) == ":") {
                time = time.substring(0, time.length - 1);

            }
            var amPmTime = splitData[2];
            $('#datepicker').attr('value', splitData[0]);
            $('#timepicker').attr('value', time + ' ' + amPmTime);

        });

    </script>
    <script>
        $('.timepicker').timepicker({
            timeFormat: 'h:mm p',
            interval: 30,
            minTime: '10',
            maxTime: '3:00pm',
            startTime: '10:00',
            dynamic: true,
            dropdown: true,
            scrollbar: true
        });

        $(function () {
            $("#datepicker2").datepicker({
                minDate: +0, maxDate: "+3M"
            });
        });

        $(document).ready(function () {
            var appointmentTime = document.getElementById('datepicker2').value;
            var splitData = "";
            if (appointmentTime.indexOf(" ") > 0) {
                splitData = appointmentTime.split(" ");

            }
            else {
                splitData = appointmentTime.split("T");

            }

            var time = splitData[1].substring(0, 5);
            if (time.slice(-1) == ":") {
                time = time.substring(0, time.length - 1);

            }
            var amPmTime = splitData[2];
            $('#datepicker2').attr('value', splitData[0]);
            $('#timepicker').attr('value', time + ' ' + amPmTime);

        });

    </script>
}

GraniteHouse/Areas/Admin/Views/Appointments/Invoice.cshtml
@model GraniteHouse.Models.ViewModel.AppointmentDetailsViewModel
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>In hóa đơn</title>
    <link rel="stylesheet" href="~/css/style.css" media="all" />
</head>
<body style="max-height:960px">
    <header class="clearfix">
        <div id="logo">
            <h1 style="font-size:35px;">Watch Shop</h1>
        </div>
        <div id="company">
            <h2 class="name">Đức Đào Company</h2>
            <div>484 Lê Văn Việt, Quận 9, TP.HCM</div>
            <div>0385639830</div>
            <div><a href="mailto:hieukio1159@gmail.com">hieukio1159@gmail.com</a></div>
        </div>
    </header>
    <main>
        <div id="details" class="clearfix">
            <div id="client">
                <div class="to">Invoice to:</div>
                <h2 class="name">@Model.Appointment.CustomerName</h2>
                <div class="address">@Model.Appointment.CustomerPhoneNumber</div>
                <div class="fa-phone">@Model.Appointment.CustomerAddress</div>
            </div>
            <div id="invoice">
                <h1>@Model.Appointment.Id</h1>
                <div class="date">Imported Date: @Model.Appointment.AppointmentCreatedDate</div>
                <div class="date">Exported Date: @Model.Appointment.AppointmentDate</div>
            </div>
        </div>       
        <partial name="~/Views/Shared/_Invoice.cshtml" model="Model.ProductsSelectedForAppointments" />
        <div id="thanks">Thank for buying!</div>
    </main>
    <footer>
    </footer>
</body>
</html>