GraniteHouse/Areas/Admin/Controllers/StatisticalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GraniteHouse.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using GraniteHouse.Models;
using GraniteHouse.Data;
using GraniteHouse.Models.ViewModel;
using System.Text;
using Microsoft.EntityFrameworkCore;

namespace GraniteHouse.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.AdminEndUser + "," + SD.SuperAdminEndUser)]
    [Area("Admin")]
    public class StatisticalController : Controller
    {
        private readonly ApplicationDbContext _db;
        private int PageSize = 10;
        public StatisticalController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            ViewBag.EarningAnnuals = _db.Appointments.Where(a => a.isCompleted == true && a.isConfirmed == true&&a.AppointmentCreatedDate.Year==DateTime.Now.Year)
                .Select(a => a.TotalAppointment).Sum();
            ViewBag.EarningMonthly = _db.Appointments.Where(a => a.isCompleted == true && a.isConfirmed == true && a.AppointmentCreatedDate.Year == DateTime.Now.Year
            &&a.AppointmentCreatedDate.Month==DateTime.Now.Month)
                .Select(a => a.TotalAppointment).Sum();
            ViewBag.NewOrders = _db.Appointments.Where(a => a.isCompleted == false && a.isConfirmed == false).Count();
            ViewBag.NewCus = _db.Customers.Where(a=>a.CusPhone!=null).Select(a=>a.CusPhone).Count();
            ViewBag.ProductOutOfStock = _db.Products.Where(a => a.Available == false).Count();
            return View();
        }

        public IActionResult EaringYear()
        {

            ViewBag.EarningThisYear = _db.Appointments.Where(a => a.isCompleted == true && a.isConfirmed == true && a.AppointmentCreatedDate.Year == DateTime.Now.Year)
                .Select(a => a.TotalAppointment).Sum();
            ViewBag.January = _db.Appointments.Where(a => a.isCompleted == true && a.isConfirmed == true && a.AppointmentCreatedDate.Month == 1 && a.AppointmentCreatedDate.Year == DateTime.Now.Year).
                Select(a => a.TotalAppointment).Sum();
            ViewBag.February = _db.Appointments.Where(a => a.isCompleted == true && a.isConfirmed == true && a.AppointmentCreatedDate.Month == 2 && a.AppointmentCreatedDate.Year == DateTime.Now.Year).
               Select(a => a.TotalAppointment).Sum();
            ViewBag.March = _db.Appointments.Where(a => a.isCompleted == true && a.isConfirmed == true && a.AppointmentCreatedDate.Month == 3 && a.AppointmentCreatedDate.Year == DateTime.Now.Year).
               Select(a => a.TotalAppointment).Sum();
            ViewBag.April = _db.Appointments.Where(a => a.isCompleted == true && a.isConfirmed == true && a.AppointmentCreatedDate.Month == 4 && a.AppointmentCreatedDate.Year == DateTime.Now.Year).
               Select(a => a.TotalAppointment).Sum();
            ViewBag.May = _db.Appointments.Where(a => a.isCompleted == true && a.isConfirmed == true && a.AppointmentCreatedDate.Month == 5 && a.AppointmentCreatedDate.Year == DateTime.Now.Year).
               Select(a => a.TotalAppointment).Sum();
            ViewBag.June = _db.Appointments.Where(a => a.isCompleted == true && a.isConfirmed == true && a.AppointmentCreatedDate.Month == 6 && a.AppointmentCreatedDate.Year == DateTime.Now.Year).
               Select(a => a.TotalAppointment).Sum();
            ViewBag.July = _db.Appointments.Where(a => a.isCompleted == true && a.isConfirmed == true && a.AppointmentCreatedDate.Month == 7 && a.AppointmentCreatedDate.Year == DateTime.Now.Year).
               Select(a => a.TotalAppointment).Sum();
            ViewBag.August = _db.Appointments.Where(a => a.isCompleted == true && a.isConfirmed == true && a.AppointmentCreatedDate.Month == 8 && a.AppointmentCreatedDate.Year == DateTime.Now.Year).
               Select(a => a.TotalAppointment).Sum();
            ViewBag.September = _db.Appointments.Where(a => a.isCompleted == true && a.isConfirmed == true && a.AppointmentCreatedDate.Month == 9 && a.AppointmentCreatedDate.Year == DateTime.Now.Year).
               Select(a => a.TotalAppointment).Sum();
            ViewBag.October = _db.Appointments.Where(a => a.isCompleted == true && a.isConfirmed == true && a.AppointmentCreatedDate.Month == 10 && a.AppointmentCreatedDate.Year == DateTime.Now.Year).
               Select(a => a.TotalAppointment).Sum();
            ViewBag.November = _db.Appointments.Where(a => a.isCompleted == true && a.isConfirmed == true && a.AppointmentCreatedDate.Month == 11 && a.AppointmentCreatedDate.Year == DateTime.Now.Year).
               Select(a => a.TotalAppointment).Sum();
            ViewBag.December = _db.Appointments.Where(a => a.isCompleted == true && a.isConfirmed == true && a.AppointmentCreatedDate.Month == 12 && a.AppointmentCreatedDate.Year == DateTime.Now.Year).
               Select(a => a.TotalAppointment).Sum();
            return View();
        }

        public async Task<IActionResult> EaringMonth(int productPage = 1, string SelectedMonth=null)
        {
            ViewBag.month = SelectedMonth;
            if(SelectedMonth==null)
            {
                ViewBag.EarningThisMonth = _db.Appointments.Where(a => a.isCompleted == true && a.isConfirmed == true && a.AppointmentCreatedDate.Month == DateTime.Now.Month && a.AppointmentCreatedDate.Year == DateTime.Now.Year)
               .Select(a => a.TotalAppointment).Sum();
               
            }
            else
            {
                ViewBag.EarningbyMonth = _db.Appointments.Where(a => a.isCompleted == true && a.isConfirmed == true && a.AppointmentCreatedDate.Month == Int32.Parse(SelectedMonth) && a.AppointmentCreatedDate.Year == DateTime.Now.Year)
             .Select(a => a.TotalAppointment).Sum();
            }
          
           
            AppointmentViewModel appointmentVM = new AppointmentViewModel()
            {
                Appointments = new List<Models.Appointments>()
            };
            StringBuilder param = new StringBuilder();

            param.Append("/Admin/Statistical/EaringMonth?productPage=:");
            param.Append("&SelectedMonth=");
            if (SelectedMonth != null)
            {
                param.Append(SelectedMonth);
            }
           
            appointmentVM.Appointments = _db.Appointments.Include(a => a.SalesPerson).OrderBy(a => a.AppointmentCreatedDate).
                Where(a => a.isCompleted == true && a.isConfirmed == true && a.AppointmentCreatedDate.Month == DateTime.Now.Month && a.AppointmentCreatedDate.Year == DateTime.Now.Year).ToList();
            if (SelectedMonth != null)
            {
                appointmentVM.Appointments = _db.Appointments.Include(a => a.SalesPerson).OrderBy(a => a.AppointmentCreatedDate).
                Where(a => a.isCompleted == true && a.isConfirmed == true && a.AppointmentCreatedDate.Month == Int32.Parse(SelectedMonth) && a.AppointmentCreatedDate.Year == DateTime.Now.Year).ToList();
            }
            var count = appointmentVM.Appointments.Count;
            
            appointmentVM.Appointments = appointmentVM.Appointments.OrderBy(a=>a.AppointmentCreatedDate)              
                .Skip((productPage - 1) * PageSize)
                .Take(PageSize).ToList();


            appointmentVM.PagingInfo = new PagingInfo
            {
                CurrentPage = productPage,
                ItemsPerPage = PageSize,
                TotalItems = count,
                urlParam = param.ToString()
            };
            return View(appointmentVM);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productList2 = (IEnumerable<Products>)(from p in _db.Products
                                                       join a in _db.ProductsSelectedForAppointment
                                                       on p.Id equals a.ProductId
                                                       where a.AppointmentId == id
                                                       select p).Include("ProductTypes").Include("Brand");

            var productList = (IEnumerable<ProductsSelectedForAppointment>)(from p in _db.Appointments
                                                                            join a in _db.ProductsSelectedForAppointment
                                                                            on p.Id equals a.AppointmentId
                                                                            where a.AppointmentId == id
                                                                            select a);
            AppointmentDetailsViewModel objAppointmentVM = new AppointmentDetailsViewModel()
            {
                Appointment = _db.Appointments.Include(a => a.SalesPerson).Where(a => a.Id == id).FirstOrDefault(),
                SalesPerson = _db.ApplicationUser.ToList(),
                ProductsSelectedForAppointments = productList.ToList(),
                Products = productList2.ToList()
            };

            return View(objAppointmentVM);
        }

    }
}

GraniteHouse/Areas/Admin/Views/Statistical/Details.cshtml
@model GraniteHouse.Models.ViewModel.AppointmentDetailsViewModel
@using GraniteHouse.Extensions
@using GraniteHouse.Utility

@{
    ViewData["Title"] = "Edit";
}



<div class="container-fluid">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h2 class="text-info">Order Detail</h2>
        </div>
        <div class="p-4 rounded row">
            <div class="col-6">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Appointment.CustomerName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Appointment.CustomerName" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Appointment.CustomerPhoneNumber"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Appointment.CustomerPhoneNumber" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Appointment.CustomerEmail"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Appointment.CustomerEmail" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Appointment.CustomerAddress"></label>
                    </div>
                    <div class="col-8">
                        <textarea asp-for="Appointment.CustomerAddress" class="form-control" disabled rows="6" style="height:50px;"></textarea>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Appointment.Note"></label>
                    </div>
                    <div class="col-8">
                        <textarea asp-for="Appointment.Note" class="form-control" disabled rows="6" style="height:50px;"></textarea>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Appointment.AppointmentCreatedDate"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Appointment.AppointmentCreatedDate" disabled id="datepicker" type="text" class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Appointment.AppointmentDate"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Appointment.AppointmentDate" disabled id="datepicker2" type="text" class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Appointment.TotalAppointment"></label>
                    </div>
                    <div class="col-8">
                        @{
                            string p = String.Format("{0:0,0}", Model.Appointment.TotalAppointment);
                        }
                        <input asp-for="@p" disabled id="datepicker" type="text" class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Appointment.SalesPerson"></label>
                    </div>
                    <div class="col-8">
                        @if (User.IsInRole(SD.AdminEndUser))
                        {
                            <input asp-for="@Model.Appointment.SalesPerson.Name" disabled class="form-control" />
                            <input asp-for="@Model.Appointment.SalesPersonId" hidden />

                        }
                        else
                        {
                            <select asp-for="@Model.Appointment.SalesPersonId" disabled asp-items="Model.SalesPerson.ToSelectListItemString(Model.Appointment.SalesPersonId)" class="form-control"></select>

                        }
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Appointment.isConfirmed"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Appointment.isConfirmed" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Appointment.isCompleted"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Appointment.isCompleted" disabled class="form-control" />
                    </div>
                </div>

            </div>
            <div class="col-6">
                @* Partial View *@
                <partial name="~/Views/Shared/_AppointmentProductDetails.cshtml" model="Model.ProductsSelectedForAppointments" />
            </div>




           
        </div>
    </div>
</div>



@section Scripts{


    <script>

        $(document).ready(function () {
            var appointmentTime = document.getElementById('datepicker').value;
            var splitData = "";
            if (appointmentTime.indexOf(" ") > 0) {
                splitData = appointmentTime.split(" ");

            }
            else {
                splitData = appointmentTime.split("T");

            }

            var time = splitData[1].substring(0, 5);
            if (time.slice(-1) == ":") {
                time = time.substring(0, time.length - 1);

            }
            var amPmTime = splitData[2];
            $('#datepicker').attr('value', splitData[0]);
            $('#timepicker').attr('value', time + ' ' + amPmTime);

        });

    </script>
    <script>

        $(document).ready(function () {
            var appointmentTime = document.getElementById('datepicker2').value;
            var splitData = "";
            if (appointmentTime.indexOf(" ") > 0) {
                splitData = appointmentTime.split(" ");

            }
            else {
                splitData = appointmentTime.split("T");

            }

            var time = splitData[1].substring(0, 5);
            if (time.slice(-1) == ":") {
                time = time.substring(0, time.length - 1);

            }
            var amPmTime = splitData[2];
            $('#datepicker2').attr('value', splitData[0]);
            $('#timepicker').attr('value', time + ' ' + amPmTime);

        });

    </script>
}

GraniteHouse/Areas/Admin/Views/Statistical/EaringMonth.cshtml
@model GraniteHouse.Models.ViewModel.AppointmentViewModel
@{
    ViewData["Title"] = "EaringMonth";
}

<div class="container-fluid">

    <div class="card shadow mb-4">

        <div class="card-header py-3">
            <div class="dropdown text-right float-right">
                <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Filter
                </button>

                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    @for (int i = 1; i <= 12; i++)
                    {
                        <a class="dropdown-item" asp-area="Admin" asp-action="EaringMonth" asp-controller="Statistical" asp-route-SelectedMonth="@i.ToString()">Month @i</a>
                    }

                </div>
            </div>
            @if (ViewBag.month == null)
            {
                <h2 class="text-info">Earnings @DateTime.Now.Month</h2>
                <h2 class="text-primary">Revenue: @ViewBag.EarningThisMonth.ToString("#,##0") Vnđ</h2>
            }
            else
            {
                <h2 class="text-info">Earnings @ViewBag.month</h2>
                <h2 class="text-primary">Revenue: @ViewBag.EarningbyMonth.ToString("#,##0") Vnđ</h2>
            }


        </div>

        <div class="card-body">

            <table class="table table-striped border">
                <tr class="table-info">
                    <th>
                        #
                    </th>
                    <th>
                        Sale Person
                    </th>
                    <th>
                        Created Date
                    </th>
                    <th>
                        Shipping Date
                    </th>
                    <th>
                        Total
                    </th>

                    <th></th>
                    <th></th>
                </tr>

                @foreach (var item in Model.Appointments)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(m => item.Id)
                        </td>

                        <td>
                            @Html.DisplayFor(m => item.SalesPerson.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(m => item.AppointmentCreatedDate)
                        </td>
                        <td>
                            @Html.DisplayFor(m => item.AppointmentDate)
                        </td>
                        <td>
                            @String.Format("{0:0,0}", item.TotalAppointment)
                        </td>
                        <td style="width:150px">
                            <div class="btn-group" role="group">
                                <a target="_blank" type="button" class="btn btn-success" asp-area="Admin" asp-action="Details" asp-controller="Statistical" asp-route-id="@item.Id">
                                    <i class="far fa-list-alt"></i>
                                </a>
                            </div>
                        </td>
                        <td>
                        </td>
                    </tr>

                }
            </table>
        </div>

    </div>
    <div page-model="@Model.PagingInfo" page-action="EaringMonth" page-classes-enabled="true"
         page-class="btn border" page-class-normal="btn btn-default active"
         page-class-selected="btn btn-primary active" class="btn-group m-1"></div>
</div>

GraniteHouse/Areas/Admin/Views/Statistical/EaringYear.cshtml
@{
    ViewData["Title"] = "EaringYear";
}





<script>
    var thang1 =@ViewBag.January;

    var thang2 =@ViewBag.February;

    var thang3 =@ViewBag.March;

    var thang4 =@ViewBag.April;

    var thang5 =@ViewBag.May;

    var thang6 =@ViewBag.June;

    var thang7 =@ViewBag.July;

    var thang8 =@ViewBag.August;

    var thang9 =@ViewBag.September;

    var thang10 =@ViewBag.October;

    var thang11 =@ViewBag.November;

    var thang12 =@ViewBag.December;

    window.onload = function () {
        var chart = new CanvasJS.Chart("chartContainer", {
            animationEnabled: true,
            theme: "light2",
            axisY: {
                title: "Unit: Vnđ"
            },
            data: [{
                type: "column",
                dataPoints: [
                    { y: thang1, label: "January" },
                    { y: thang2, label: "February" },
                    { y: thang3, label: "March" },
                    { y: thang4, label: "April" },
                    { y: thang5, label: "May" },
                    { y: thang6, label: "June" },
                    { y: thang7, label: "July" },
                    { y: thang8, label: "August" },
                    { y: thang9, label: "September" },
                    { y: thang10, label: "October" },
                    { y: thang11, label: "November" },
                    { y: thang12, label: "December" }
                ]
            }]
        });
        chart.render();

    }
</script>

<div class="container-fluid">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h2 class="text-info">Earnings @DateTime.Now.Year</h2>
            <h2 class="text-success">Total Revenue: @ViewBag.EarningThisYear.ToString("#,##0") Vnđ</h2>
        </div>
        <div class="card-body">
            <div id="chartContainer" style="height: 370px; width: 100%;margin-top:20px;"></div>
        </div>       
    </div>
    
</div>


<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>

GraniteHouse/Areas/Admin/Views/Statistical/Index.cshtml
    <div class="container-fluid">
        <a asp-area="Admin" asp-action="Index" asp-controller="Statistical"><h2 class="text-info"> Statistical</h2></a>
        <div class="row">
            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-success shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-success text-uppercase mb-1" style="font-size:15px;"><a class="text-success" asp-area="Admin" asp-action="EaringYear" asp-controller="Statistical">Earnings Year(@DateTime.Now.Year)</a></div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">@ViewBag.EarningAnnuals.ToString("#,##0") Vnđ</div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-primary shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1" style="font-size:15px;"><a class="text-primary" asp-area="Admin" asp-action="EaringMonth" asp-controller="Statistical">Earnings Month(@DateTime.Now.Month)</a></div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">@ViewBag.EarningMonthly.ToString("#,##0") Vnđ</div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-calendar fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>



            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-info shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-info text-uppercase mb-1" style="font-size:15px;"><a class="text-info" asp-area="Admin" asp-action="Index" asp-controller="Appointments">New Orders</a></div>
                                <div class="row no-gutters align-items-center">
                                    <div class="col-auto">
                                        <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">@ViewBag.NewOrders</div>
                                    </div>

                                </div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Pending Requests Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-warning shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-warning text-uppercase mb-1" style="font-size:15px;"><a class="text-warning" asp-area="Admin" asp-action="Index" asp-controller="Customer">New Customer</a></div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">@ViewBag.NewCus</div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-user-plus fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-danger shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-danger text-uppercase mb-1" style="font-size:15px;"><a class="text-danger" asp-area="Admin" asp-action="Index" asp-controller="Products" asp-route-StatusFalse="Falses">Products Out of Stock!</a></div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">@ViewBag.ProductOutOfStock</div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-shopping-cart fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>